# Generated by Django 2.2.16 on 2023-11-24 20:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите Имя и Отчество', verbose_name='Имя и Отчество')),
                ('surname', models.TextField(help_text='Введите Фамилию', verbose_name='Фамилия')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Введите номер телефона', max_length=31, verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Введите email', max_length=254, verbose_name='Email')),
                ('href_whatsapp', models.URLField(help_text='Введите ссылку на WhatsApp', verbose_name='Ссылка на WhatsApp')),
                ('href_vk', models.URLField(help_text='Введите ссылку на VK', verbose_name='Ссылка на VK')),
            ],
        ),
    ]
