# Generated by Django 2.2.16 on 2023-12-03 19:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст', verbose_name='Текст')),
                ('work_time', models.TextField(help_text='Введите период работы', verbose_name='Период работы')),
                ('work_place', models.TextField(help_text='Введите место работы', verbose_name='Место работы')),
                ('id_num', models.TextField(help_text='Введите номер удостоверения', verbose_name='Номер удостоверения')),
                ('id_url', models.URLField(help_text='Введите ссылку на удостоверение', verbose_name='Ссылка на удостоверение')),
            ],
            options={
                'verbose_name': 'Обо мне',
                'verbose_name_plural': 'Обо мне',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите Имя и Отчество', verbose_name='Имя и Отчество')),
                ('surname', models.TextField(help_text='Введите Фамилию', verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона', max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Введите email', max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(help_text='Добавьте фото', upload_to='images/', verbose_name='Фото')),
                ('address', models.TextField(help_text='Введите Адрес', verbose_name='Адрес')),
                ('url_address', models.TextField(help_text='Введите ссылку на адрес', verbose_name='Ссылка на адрес')),
                ('url_whatsapp', models.URLField(help_text='Введите ссылку на WhatsApp', verbose_name='Ссылка на WhatsApp')),
                ('url_vk', models.URLField(help_text='Введите ссылку на VK', verbose_name='Ссылка на VK')),
                ('map', models.URLField(help_text='Введите код карты', verbose_name='Код карты')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Введите заголовок', verbose_name='Заголовок')),
                ('image', models.ImageField(help_text='Добавьте картинку', upload_to='images/', verbose_name='Картинка')),
                ('gif', models.ImageField(help_text='Добавьте GIF к посту', upload_to='gif/', verbose_name='GIF к посту')),
                ('description', models.TextField(help_text='Введите текст публикации', verbose_name='Текст публикации')),
            ],
            options={
                'verbose_name': 'Публикации',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='VideoAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Добавьте видео', upload_to='videos/', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
