# Generated by Django 2.2.16 on 2023-11-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст', verbose_name='Текст')),
                ('work_time', models.TextField(help_text='Введите период работы', verbose_name='Период работы')),
                ('work_place', models.TextField(help_text='Введите место работы', verbose_name='Место работы')),
                ('id_num', models.TextField(help_text='Введите номер удостоверения', verbose_name='Номер удостоверения')),
                ('id_url', models.URLField(help_text='Введите ссылку на удостоверение', verbose_name='Ссылка на удостоверение')),
            ],
        ),
    ]
