# Generated by Django 2.2.16 on 2023-12-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoabout',
            name='photo_to_video',
            field=models.ImageField(default=0, help_text='Добавьте фото к видео', upload_to='images/', verbose_name='Фото к видео'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='map',
            field=models.URLField(help_text='Введите ссылку на карту', verbose_name='Ссылка на карту'),
        ),
    ]
