# Generated by Django 2.2.16 on 2023-12-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231214_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoabout',
            name='photo_to_video',
            field=models.ImageField(help_text='Добавьте фото к видео', upload_to='images/', verbose_name='Фото к видео'),
        ),
    ]
