# Generated by Django 2.2.16 on 2023-11-24 22:03

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='', help_text='Введите Адрес', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='href_address',
            field=models.TextField(default='', help_text='Введите ссылку на адрес', verbose_name='Ссылка на адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Введите номер телефона', max_length=31, verbose_name='Телефон'),
        ),
    ]
