# Generated by Django 2.2.16 on 2023-11-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20231125_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ask',
        ),
    ]
