# Generated by Django 2.2.16 on 2023-11-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_ask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта отправителя')),
                ('message', models.TextField(verbose_name='Сообщение отправителя')),
            ],
            options={
                'verbose_name': 'Контактная форма',
                'verbose_name_plural': 'Контактная форма',
            },
        ),
    ]
