# Generated by Django 2.2.16 on 2023-11-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='description',
            field=models.TextField(help_text='Введите текст публикации', verbose_name='Текст публикации'),
        ),
    ]
