# Generated by Django 2.2.16 on 2023-11-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20231125_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='gif',
            field=models.ImageField(default='', help_text='Добавьте GIF к посту', upload_to='', verbose_name='GIF к посту'),
        ),
    ]
