# Generated by Django 2.2.16 on 2023-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_publications_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='gif',
            field=models.ImageField(help_text='Добавьте GIF к посту', upload_to='', verbose_name='GIF к посту'),
        ),
    ]
