# Generated by Django 2.2.16 on 2023-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20231125_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='gif',
            field=models.ImageField(help_text='Добавьте GIF к посту', upload_to='static/gif/', verbose_name='GIF к посту'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='image',
            field=models.ImageField(help_text='Добавьте картинку', upload_to='static/images/', verbose_name='Картинка'),
        ),
    ]
