# Generated by Django 2.2.16 on 2023-11-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20231125_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ask',
        ),
    ]
