# Generated by Django 2.2.16 on 2023-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', help_text='Добавьте фото', upload_to='images/', verbose_name='Фото'),
        ),
    ]
