# Generated by Django 2.2.16 on 2023-11-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='href_address',
            new_name='url_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='href_vk',
            new_name='url_vk',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='href_whatsapp',
            new_name='url_whatsapp',
        ),
        migrations.AddField(
            model_name='profile',
            name='map',
            field=models.TextField(default='', help_text='Введите код карты', verbose_name='Код карты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(help_text='Добавьте фото', upload_to='images/', verbose_name='Фото'),
        ),
    ]
