# Generated by Django 2.2.16 on 2023-11-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20231129_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='map',
            field=models.TextField(help_text='Введите код карты', verbose_name='Код карты'),
        ),
    ]
